[package]
name = "rust_slvs"
version = "0.1.0"
edition = "2021"
exclude = [
    "/solvespace/*",
]
include = [
    "/solvespace/include/slvs.h",
    "/solvespace/src/*",
    "/solvespace/extlib/eigen/*",
    "/solvespace/extlib/mimalloc/include/*",
    "/solvespace/extlib/mimalloc/src/*",
    "/src/*",
    "/.gitignore",
    "/.gitmodules",
    "/build.rs",
    "/README.md",
]

[build-dependencies]
bindgen = "0.64.0"
cc = "1.0.79"
cmake = "0.1.49"
